BROKER = "PAPER"
BOT_NAME = "Option Buying Bot"
VERSION = "1.0"
PAPER_TRADING = True

ATR_MULTIPLIER = 1.5
RISK_REWARD = 2

CAPITAL = 50000
RISK_PER_TRADE = 2
LOT_SIZE = 75

STRIKE_STEP = 50
STRIKE_OFFSET = 0

RUN_BACKTEST = False
DATA_PROVIDER = "YFINANCE"

BREAK_EVEN_ENABLE = True

BREAK_EVEN_TRIGGER = 20

PARTIAL_EXIT_ENABLE = True

PARTIAL_EXIT_PERCENT = 50
TESTING_MODE = True